/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tfile;
import java.sql.*;
import java.util.*;
/**
 *
 * @author New
 */
public class reduce extends javax.swing.JFrame {
    public static ArrayList  ar=new ArrayList();
    public static ArrayList ar2=new ArrayList();
    public static ArrayList ori=new ArrayList();
    public static ArrayList ori2=new ArrayList();
    public static float sim[]=new float[100000];
    public static String b[]=new String[100000];
    public static String a[]=new String[100000];
    int n2[]=new int[group.no];
    public static int n;
    public static int no;
    int j1[]=new int[group.no];
    float tot[]=new float[group.no];
    public static float simi[];
            public static float t[]=new float[group.no];
    
    Statement st;
    ResultSet rs,rs1,rs2;
    /**
     * Creates new form reduce
     */
    public reduce() {
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/fileconversion","root","");
        st=con.createStatement();
      
        }
        catch(Exception e){
        System.out.println("SQL Exceptiom"+e);
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Reduce Redundant Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Original Document");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(49, 53, 159, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comparitive Document");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(255, 53, 178, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(42, 86, 166, 352);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(255, 86, 166, 352);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Similarity");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 450, 133, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 450, 131, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Similarity");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 50, 80, 22);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(450, 90, 166, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 740, 500);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collweb.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            int i=0,j=0;
            float val=0;
        rs=st.executeQuery("select words from stopwords");
        while(rs.next()){
            a[i]=rs.getString(1);
            jTextArea1.append(a[i]+"\n");
            i++;
        }
        System.out.println("i"+i);
        for(int z=0;z<group.no;z++){
            j=0;
        rs2=st.executeQuery("select words from stopwords"+z);
        while(rs2.next()){
            b[j]=rs2.getString(1);
            jTextArea2.append(b[j]+"\n");
            j++;
        }
        j1[z]=j;
         System.out.println("j"+j+"stopword"+z);
          int occ=0;
        if(i>j){
             occ=j;
             
         }
         else{
             occ=i;
         }
        int x1=0;
      System.out.println("occ "+occ);
        val=0;
        for(i=0;i<occ;i++){
        String simil=Double.toString(similarity(a[i],b[i]));
            sim[i]=Float.parseFloat(simil);
           jTextArea3.append(simil+"\n");
           x1++;
          val+=sim[i];
          sim[i]=0;
        }
        System.out.println("x1"+x1);
        System.out.println("sim"+val);
        
        tot[z]=  val;
        n2[z]=x1;
        System.out.println("Group.no "+group.no+ " z "+z);
        System.out.println("tot[z] "+tot[z]+"n2[z] "+n2[z]);
       t[z]=tot[z]/n2[z];
        System.out.println("total    "+group.no);
        System.out.println("NO of rows "+n2[z]);
        System.out.println("Similarity value   "+t[z]);
        }
        

        }
        catch(Exception e){
            System.out.println("Exception 1"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        comp c=new comp();
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new reduce().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

    private double similarity(String s, String r) {
        //throw new UnsupportedOperationException("Not yet implemented");
         int m=s.length();
        
        int n=r.length();
        
        double big=0;
        if(m>n)
        {
            big=m;
            
         }
        else
        {
            big=n;
           
        }
        big=(big-editDistance(s,r))/big;
        return big;
    }

    private double editDistance(String s, String r) {
        int m=s.length();
        int n=r.length();
        
        int[][] d=new int[m+1][n+1];
        for(int i=0;i<=m;i++)
        {
            d[i][0]=i;
        }
        for(int j=0;j<=n;j++)
        {
            d[0][j]=j;
        }
        for(int j=1;j<=n;j++)
        {
            for(int i=1;i<=m;i++)
            {
                if(s.charAt(i-1)==r.charAt(j-1))
                {
                    d[i][j]=d[i-1][j-1];
                }
                else
                {
                    d[i][j]=min((d[i-1][j]+1),(d[i][j-1]+1),d[i-1][j-1]+1);
                }
            }
        }
       
        return (d[m][n]);
    }

    private int min(int i, int i0, int i1) {
        return(Math.min((Math.min(i,i0)), i1));
    }
}
